CREATE TABLE IF NOT EXISTS Users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(35) NOT NULL,
        email varchar NOT NULL,
        country varchar NOT NULL,
        CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
);